import { PeerConnection } from "./PeerConnection";
import { WebRTCConnection } from "./WebRTCConnection";
import { DataChannel } from './DataChannel';
import { BandwidthConstraints } from "./BandwidthConstraints";
import { Controller } from "../Controller";
import { IE2EE } from '../E2EE/EncodeDecode';
export declare class WebRTC {
    private brokerController;
    private rtcConfig;
    peers: Map<string, WebRTCConnection>;
    peer: RTCPeerConnection;
    dataChannels: Map<string, DataChannel>;
    localPeerId: string;
    context: any;
    localStreams: Array<any>;
    errors: Array<any>;
    bandwidthConstraints: BandwidthConstraints;
    e2ee: IE2EE;
    isEncrypted: boolean;
    onError: (err: any) => void;
    onContextCreated: (peerConnection: PeerConnection) => void;
    onContextChanged: (context: {
        context: string;
        peerId: string;
    }) => void;
    onRemoteAudioTrack: (track: MediaStreamTrack, connection: WebRTCConnection, event: RTCTrackEvent) => void;
    onRemoteVideoTrack: (track: MediaStreamTrack, connection: WebRTCConnection, event: RTCTrackEvent) => void;
    onRemoteTrack: (track: MediaStreamTrack, connection: WebRTCConnection, event: RTCTrackEvent) => void;
    onRemoteTrackLost: (track: MediaStreamTrack, connection: WebRTCConnection, event: MediaStreamTrackEvent) => void;
    onLocalStream: (stream: MediaStream) => void;
    onContextConnected: (webRTCConnection: WebRTCConnection, rtcPeerConnection: RTCPeerConnection) => void;
    onContextDisconnected: (webRTCConnection: WebRTCConnection, rtcPeerConnection: RTCPeerConnection) => void;
    private onConnectTo;
    private onConnected;
    onDisconnected(peerId: string): void;
    constructor(brokerController: Controller, rtcConfig: any, e2ee?: IE2EE);
    addTrackToPeers(track: MediaStreamTrack): void;
    removeTrackFromPeers(track: MediaStreamTrack): void;
    getRtpSenders(peerId: string): Array<RTCRtpSender>;
    getRtpReceivers(peerId: string): Array<RTCRtpReceiver>;
    setBandwithConstraints(videobandwidth: number, audiobandwidth: number): void;
    private setMediaBitrates;
    private setMediaBitrate;
    createDataChannel(name: string): DataChannel;
    removeDataChannel(name: string): void;
    private addError;
    private onCandidate;
    private onAnswer;
    private onOffer;
    addLocalStream(stream: any): WebRTC;
    addIceServer(iceServer: RTCIceServer): WebRTC;
    private removePeerConnection;
    private createPeerConnection;
    cleanUp(id: string): void;
    findPeerConnection(id: string): WebRTCConnection;
    reconnectAll(): Array<PeerConnection>;
    private getPeerConnection;
    private createOffer;
    disconnect(): void;
    disconnectPeer(id: string): void;
    connect(peerConnections: Array<PeerConnection>): WebRTC;
    changeContext(context: string): WebRTC;
    private connectPeers;
    connectContext(): void;
}
